# Generated by Django 4.2.5 on 2023-09-24 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_beca_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Facultad',
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('nit', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Universidad',
            },
        ),
        migrations.RenameField(
            model_name='beca',
            old_name='name',
            new_name='nombre',
        ),
        migrations.CreateModel(
            name='Union_U_F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.facultad')),
                ('univeridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.universidad')),
            ],
        ),
    ]
