# Generated by Django 4.2.5 on 2023-09-24 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_facultad_universidad_rename_name_beca_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion_Becas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('facultad', 'facultad'), ('beca', 'beca')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('Entidad', 'Entidad'), ('Universidad', 'Universidad')], default='Universidad', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='beca',
            name='tipo',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Extranjera', 'Extranjera')], default='Nacional', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='union_u_f',
            constraint=models.UniqueConstraint(fields=('univeridad', 'facultad'), name='unique_foraneas'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='Configuracion_Becas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.configuracion_becas'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracion_becas',
            name='Beca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.beca'),
        ),
        migrations.AddField(
            model_name='configuracion_becas',
            name='Union_U_F',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.union_u_f'),
        ),
    ]
