# Generated by Django 4.2.5 on 2023-09-24 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_configuracion_becas_favoritos_fundacion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='union_u_f',
            name='unique_foraneas',
        ),
        migrations.AddField(
            model_name='configuracion_becas',
            name='Fundacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.fundacion'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='configuracion_becas',
            constraint=models.UniqueConstraint(fields=('Union_U_F', 'Beca', 'Fundacion'), name='unique_foraneas_configuracion'),
        ),
        migrations.AddConstraint(
            model_name='favoritos',
            constraint=models.UniqueConstraint(fields=('usuario', 'Configuracion_Becas'), name='unique_foraneas_favoritos'),
        ),
        migrations.AddConstraint(
            model_name='union_u_f',
            constraint=models.UniqueConstraint(fields=('univeridad', 'facultad'), name='unique_foraneas_union'),
        ),
    ]
