# Generated by Django 4.2.5 on 2023-09-24 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_remove_favoritos_unique_foraneas_favoritos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favoritos',
            new_name='Becas_Fav',
        ),
    ]
