# Generated by Django 4.2.5 on 2023-09-24 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_rename_favoritos_becas_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='beca',
            name='Descripcion',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Facultad_fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.facultad')),
            ],
        ),
        migrations.AddField(
            model_name='beca',
            name='Documentos',
            field=models.ManyToManyField(to='app.documentos'),
        ),
        migrations.AddField(
            model_name='beca',
            name='Requisitos',
            field=models.ManyToManyField(to='app.requisitos'),
        ),
    ]
